/**
 * Scanner Understanding Lab — LexiScan house-tour data (nameEn / nameEs).
 * Product content preserved from legacy hitl/microworld tabbed shell.
 */
window.PLAYGROUND_DATA = {
  meta: {
    titleEn: "HITL Review House — VertiGreen",
    titleEs: "Casa de revisión HITL — VertiGreen",
    subtitleEn: "Synthetic dataroom · ≤10 min loop · local lock-in",
    subtitleEs: "Dataroom sintético · bucle ≤10 min · bloqueo local",
    product: "cth-data-room-scanner",
    format: "lexiscan-house-tour-v1",
  },

  config: {
    repoUrl: "https://github.com/gideonblaauw-creator/cth-data-room-scanner",
    notionDecisionsDb: "https://app.notion.com/p/bb52cfa45b6744e59983528480fbab4b",
    defaultFindingsUrl: "defaults/findings-hitl-20260908-214515.json",
    storage: {
      prefix: "cth_scanner_playground_",
      legacy: {
        decisions: "cth_microworld_decisions",
        quiz: "cth_microworld_quiz",
        clarifications: "cth_microworld_clarifications",
        lang: "cth_microworld_lang",
        welcome: "cth_scanner_playground_welcome",
        room: "cth_scanner_playground_room",
      },
    },
    notionPages: [
      { nameEn: "Explainer", nameEs: "Explicador", url: "https://app.notion.com/p/3d5dfee50be9816db4dec71e885a1f7d" },
      { nameEn: "Microworld Notion", nameEs: "Micromundo Notion", url: "https://app.notion.com/p/3d9dfee50be981ab8bd4ff5fd40c8e35" },
      { nameEn: "Lab Home", nameEs: "Inicio del lab", url: "https://app.notion.com/p/3d5dfee50be98174a045febce0fc4b3d" },
    ],
  },

  /** Floor-plan rooms — corridor links use `exits` ids. */
  rooms: [
    {
      id: "welcome",
      nameEn: "Foyer",
      nameEs: "Recibidor",
      type: "welcome",
      grid: { row: 0, col: 0 },
      exits: ["context"],
    },
    {
      id: "context",
      nameEn: "Context Room",
      nameEs: "Sala de contexto",
      type: "content",
      grid: { row: 0, col: 1 },
      exits: ["welcome", "explainer"],
      blocks: [
        {
          headingEn: "Why this microworld?",
          headingEs: "¿Por qué este micromundo?",
          bodyEn:
            "The <strong>Dataroom Reviewer HITL loop</strong> trains reviewers to consciously agree, override, or defer on agent findings before they enter the shared Notion Decisions database. This house tour replaces the legacy tabbed shell with LexiScan-standard rooms.",
          bodyEs:
            "El <strong>bucle HITL del revisor de dataroom</strong> entrena a los revisores a aceptar, anular o aplazar hallazgos del agente antes de entrar en la base Decisions de Notion.",
        },
        {
          headingEn: "Sample company: VertiGreen Robotics",
          headingEs: "Empresa de muestra: VertiGreen Robotics",
          bodyEn:
            "A fictional cleantech startup (precision irrigation / AgriTech) with synthetic fixtures under <code>fixtures/sample-dataroom/</code>. No real client data.",
          bodyEs:
            "Startup cleantech ficticia con fixtures sintéticos en <code>fixtures/sample-dataroom/</code>.",
        },
        {
          headingEn: "5-beat flow",
          headingEs: "Flujo de 5 pasos",
          flowSteps: [
            { nameEn: "Home", nameEs: "Inicio", descEn: "Lab entry", descEs: "Entrada al lab" },
            { nameEn: "Explainer", nameEs: "Explicador", descEn: "Quiz gate", descEs: "Puerta del cuestionario" },
            { nameEn: "Micro world", nameEs: "Micromundo", descEn: "Lock decisions", descEs: "Bloquear decisiones" },
            { nameEn: "Decisions DB", nameEs: "Base Decisions", descEn: "Shared space", descEs: "Espacio compartido" },
            { nameEn: "Next", nameEs: "Siguiente", descEn: "Push / approve", descEs: "Enviar / aprobar" },
          ],
        },
        {
          headingEn: "What gets locked",
          headingEs: "Qué se bloquea",
          bodyEn:
            "Each gate finding (F001–F010 style) records: <code>finding_id</code>, <code>fixture_path</code>, agent label/suggestion, your <strong>agree / override / defer</strong>, rationale (≥8 chars), and <code>locked_at</code>. Exported as <code>microworld-locks.json</code>.",
          bodyEs:
            "Cada hallazgo registra finding_id, fixture, decisión humana, justificación y locked_at en microworld-locks.json.",
        },
        {
          headingEn: "Why auto-push failed (by design)",
          headingEs: "Por qué falló el auto-push (por diseño)",
          bodyEn:
            "The browser <strong>must not hold Notion secrets</strong>. Tokens live in Infisical / env only (SoT). After lock-in, download JSON locally; <strong>Infra or Hands</strong> push via <code>scripts/push_microworld_to_notion.py</code>.",
          bodyEs:
            "El navegador no debe contener secretos de Notion. Los tokens viven solo en Infisical/env.",
          code: "# NOTION_API_TOKEN from Infisical (env only — never embed in HTML)\npython scripts/push_microworld_to_notion.py --dry-run\npython scripts/push_microworld_to_notion.py",
        },
      ],
    },
    {
      id: "explainer",
      nameEn: "Explainer Hall",
      nameEs: "Sala del explicador",
      type: "quiz",
      grid: { row: 0, col: 2 },
      exits: ["context", "corridor"],
      gateFor: ["corridor"],
      labelCards: [
        {
          id: "auto_ok",
          nameEn: "auto_ok",
          nameEs: "auto_ok",
          descEn: "Safe to include with standard diligence.",
          descEs: "Seguro para incluir con diligencia estándar.",
        },
        {
          id: "needs_human",
          nameEn: "needs_human",
          nameEs: "needs_human",
          descEn: "Reviewer must confirm before external share.",
          descEs: "El revisor debe confirmar antes de compartir.",
        },
        {
          id: "unclear",
          nameEn: "unclear",
          nameEs: "unclear",
          descEn: "Conflicting signals; legal or financial follow-up.",
          descEs: "Señales conflictivas; seguimiento legal/financiero.",
        },
      ],
      humanDecisions: [
        { id: "agree", nameEn: "agree", nameEs: "agree", descEn: "Accept agent label and suggested action.", descEs: "Aceptar etiqueta y acción del agente." },
        { id: "override", nameEn: "override", nameEs: "override", descEn: "Different label or action (document in Rationale).", descEs: "Etiqueta o acción diferente (documentar en Justificación)." },
        { id: "defer", nameEn: "defer", nameEs: "defer", descEn: "Needs more context or external counsel.", descEs: "Necesita más contexto o asesoría externa." },
      ],
    },
    {
      id: "corridor",
      nameEn: "Decision Corridor",
      nameEs: "Pasillo de decisiones",
      type: "corridor",
      grid: { row: 0, col: 3 },
      exits: ["explainer"],
      requiresQuiz: true,
      descEn: "Choose a finding door. Pass the Explainer quiz to unlock.",
      descEs: "Elija una puerta de hallazgo. Apruebe el cuestionario del Explicador para desbloquear.",
    },
    {
      id: "gh-repo",
      nameEn: "Repo Archive",
      nameEs: "Archivo del repo",
      type: "link",
      grid: { row: 1, col: 0 },
      exits: ["corridor", "clarifications"],
      sidebar: true,
    },
    {
      id: "clarifications",
      nameEn: "Clarifications Nook",
      nameEs: "Rincón de aclaraciones",
      type: "clarifications",
      grid: { row: 1, col: 1 },
      exits: ["gh-repo"],
      sidebar: true,
    },
  ],

  /** Decision-door rooms — one per gate finding (dynamic from findings). */
  decisionRoomTemplate: {
    type: "decision",
    gridRow: 2,
    requiresQuiz: true,
  },

  quizQuestions: [
    {
      id: "Q1",
      questionEn: "Why does `fake-invoice-redacted.txt` receive `needs_human` instead of `auto_ok`?",
      questionEs: "¿Por qué `fake-invoice-redacted.txt` recibe `needs_human` en lugar de `auto_ok`?",
      optionsEn: [
        "It contains a partial IBAN that may need redaction confirmation",
        "It is written in Dutch",
        "It has no date field",
        "It references a patent number",
      ],
      optionsEs: [
        "Contiene un IBAN parcial que puede necesitar confirmación de redacción",
        "Está escrito en holandés",
        "No tiene campo de fecha",
        "Hace referencia a un número de patente",
      ],
      answer: 0,
    },
    {
      id: "Q2",
      questionEn: "What label should ambiguous cap-table / SAFE language typically get?",
      questionEs: "¿Qué etiqueta debe recibir típicamente el lenguaje ambiguo de cap table / SAFE?",
      optionsEn: ["auto_ok", "needs_human", "unclear", "skip"],
      optionsEs: ["auto_ok", "needs_human", "unclear", "skip"],
      answer: 2,
    },
    {
      id: "Q3",
      questionEn: "Which Geoffrey Litt concept maps to the Decisions database in Notion?",
      questionEs: "¿Qué concepto de Geoffrey Litt corresponde a la base Decisions en Notion?",
      optionsEn: ["Explanations", "Micro worlds", "Shared spaces", "Literate programming"],
      optionsEs: ["Explicaciones", "Micromundos", "Espacios compartidos", "Programación literaria"],
      answer: 2,
    },
    {
      id: "Q4",
      questionEn: "When can a run be marked Approved in the HITL gate?",
      questionEs: "¿Cuándo se puede marcar un run como Aprobado en la puerta HITL?",
      optionsEn: [
        "When the agent finishes scanning",
        "Only when quiz passed or explicitly waived",
        "When all files are auto_ok",
        "Never — always manual",
      ],
      optionsEs: [
        "Cuando el agente termina de escanear",
        "Solo cuando el cuestionario se pasó o se renunció explícitamente",
        "Cuando todos los archivos son auto_ok",
        "Nunca — siempre manual",
      ],
      answer: 1,
    },
    {
      id: "Q5",
      questionEn: "What does the microworld scrubber let a reviewer do?",
      questionEs: "¿Qué permite hacer el scrubber del micromundo a un revisor?",
      optionsEn: [
        "Edit production scanner code",
        "Step through synthetic agent reasoning per finding",
        "Connect to live Notion",
        "Upload to Google Drive",
      ],
      optionsEs: [
        "Editar código del escáner de producción",
        "Recorrer el razonamiento sintético del agente por hallazgo",
        "Conectar a Notion en vivo",
        "Subir a Google Drive",
      ],
      answer: 1,
    },
  ],

  momentLabels: {
    iban_redaction: { nameEn: "IBAN redaction", nameEs: "Redacción IBAN" },
    unaudited_financials: { nameEn: "Unaudited financials", nameEs: "Finanzas no auditadas" },
    safe_cap_table: { nameEn: "SAFE / cap table", nameEs: "SAFE / tabla de capitalización" },
    hallucinated_metric: { nameEn: "Hallucinated metric", nameEs: "Métrica no respaldada" },
    impact_metrics: { nameEn: "Impact metrics", nameEs: "Métricas de impacto" },
    unsigned_contract: { nameEn: "Unsigned contract", nameEs: "Contrato sin firmar" },
    overview_metric: { nameEn: "Overview metric", nameEs: "Métrica del resumen" },
    general: { nameEn: "General review", nameEs: "Revisión general" },
  },

  i18n: {
    en: {
      welcomeTitle: "Welcome to the Review House",
      welcomeBody: "Walk the floor plan: context → quiz → decision doors → ledger export. Progress saves locally.",
      welcomeStart: "Enter the house",
      welcomeSkip: "Skip intro",
      floorPlan: "Floor plan",
      currentRoom: "You are here",
      langEn: "EN",
      langEs: "ES",
      reset: "Reset progress",
      resetConfirm: "Clear all local progress (quiz, decisions, clarifications)?",
      ledger: "Decisions ledger",
      ledgerEmpty: "No locked decisions yet.",
      downloadJson: "Download JSON",
      downloadMd: "Download Markdown",
      copyJson: "Copy JSON",
      copyMd: "Copy Markdown",
      openNotion: "Open Decisions DB",
      quizGate: "Complete the Explainer quiz to unlock decision doors.",
      quizPassed: "Quiz passed — decision corridor unlocked.",
      submitQuiz: "Submit quiz",
      retakeQuiz: "Retake",
      goCorridor: "Go to corridor",
      quizScore: (s, t) => `Score ${s}/${t}`,
      allAnswered: "Answer all 5 questions.",
      reviewRetake: "Review labels above and retake.",
      locked: "Locked",
      draft: "Draft saved",
      unlocked: "Unreviewed",
      agree: "Agree with agent",
      override: "Override",
      defer: "Defer",
      rationale: "Rationale (required, min 8 chars)",
      saveDraft: "Save draft",
      lockDecision: "Lock decision",
      lockConfirm: "Lock this decision? It becomes immutable until you explicitly unlock.",
      unlock: "Unlock",
      unlockConfirm: "Unlock this decision? You will need to re-lock with a new rationale.",
      rationaleShort: "Rationale must be at least 8 characters.",
      pickDecision: "Choose agree, override, or defer before locking.",
      scrubber: "Reasoning scrubber",
      matched: "Matched",
      step: (i, n) => `Step ${i} / ${n}`,
      moment: "Review moment",
      file: "File",
      pillar: "Pillar",
      rule: "Rule fired",
      label: "Label",
      suggestion: "Agent suggestion",
      decision: "Your decision",
      progress: (l, t) => `${l} / ${t} locked`,
      allLocked: "All decisions locked",
      locksReady: "Locks ready — not yet in Notion",
      locksHint: "Download or copy JSON/MD, then push via Infra/Hands (token stays in env).",
      loadFindings: "Load findings",
      corridorLocked: "Pass the Explainer quiz first.",
      addClarification: "Add clarification",
      exportClarifications: "Export clarifications.json",
      noClarifications: "No open clarifications yet.",
      findingId: "Finding ID",
      note: "Note",
      remove: "Remove",
      pushRecipe: "Push recipe (Infisical / env token only)",
      relatedNotion: "Related Notion pages",
      completedRun: "Gideon's completed run: run_id hitl-20260908-214515 with locks F001, F004, F005, F006, F008, F009, F010.",
      ghPaths: "Relevant paths",
      fixtureMap: "Fixture → finding map (current run)",
      humanDecisionsHeading: "Human decisions",
      agentLabelsHeading: "Agent labels",
      quizHeading: "Quiz (5 questions)",
    },
    es: {
      welcomeTitle: "Bienvenido a la Casa de revisión",
      welcomeBody: "Recorra el plano: contexto → cuestionario → puertas de decisión → exportar ledger. El progreso se guarda localmente.",
      welcomeStart: "Entrar a la casa",
      welcomeSkip: "Omitir intro",
      floorPlan: "Plano",
      currentRoom: "Está aquí",
      langEn: "EN",
      langEs: "ES",
      reset: "Reiniciar progreso",
      resetConfirm: "¿Borrar todo el progreso local (cuestionario, decisiones, aclaraciones)?",
      ledger: "Ledger de decisiones",
      ledgerEmpty: "Sin decisiones bloqueadas aún.",
      downloadJson: "Descargar JSON",
      downloadMd: "Descargar Markdown",
      copyJson: "Copiar JSON",
      copyMd: "Copiar Markdown",
      openNotion: "Abrir base Decisions",
      quizGate: "Complete el cuestionario del Explicador para desbloquear las puertas.",
      quizPassed: "Cuestionario aprobado — pasillo desbloqueado.",
      submitQuiz: "Enviar cuestionario",
      retakeQuiz: "Repetir",
      goCorridor: "Ir al pasillo",
      quizScore: (s, t) => `Puntuación ${s}/${t}`,
      allAnswered: "Responda las 5 preguntas.",
      reviewRetake: "Revise las etiquetas y repita.",
      locked: "Bloqueada",
      draft: "Borrador",
      unlocked: "Sin revisar",
      agree: "De acuerdo",
      override: "Anular",
      defer: "Aplazar",
      rationale: "Justificación (mín. 8 caracteres)",
      saveDraft: "Guardar borrador",
      lockDecision: "Bloquear decisión",
      lockConfirm: "¿Bloquear? Será inmutable hasta desbloquear explícitamente.",
      unlock: "Desbloquear",
      unlockConfirm: "¿Desbloquear? Deberá volver a bloquear con nueva justificación.",
      rationaleShort: "La justificación debe tener al menos 8 caracteres.",
      pickDecision: "Elija de acuerdo, anular o aplazar.",
      scrubber: "Scrubber",
      matched: "Coincidencia",
      step: (i, n) => `Paso ${i} / ${n}`,
      moment: "Momento",
      file: "Archivo",
      pillar: "Pilar",
      rule: "Regla",
      label: "Etiqueta",
      suggestion: "Sugerencia",
      decision: "Su decisión",
      progress: (l, t) => `${l} / ${t} bloqueadas`,
      allLocked: "Todas las decisiones bloqueadas",
      locksReady: "Bloqueos listos — aún no en Notion",
      locksHint: "Descargue o copie JSON/MD, luego envíe vía Infra/Hands (token en env).",
      loadFindings: "Cargar hallazgos",
      corridorLocked: "Primero apruebe el cuestionario del Explicador.",
      addClarification: "Añadir aclaración",
      exportClarifications: "Exportar clarifications.json",
      noClarifications: "Sin aclaraciones abiertas.",
      findingId: "ID hallazgo",
      note: "Nota",
      remove: "Eliminar",
      pushRecipe: "Receta de envío (token solo en env / Infisical)",
      relatedNotion: "Páginas Notion relacionadas",
      completedRun: "Run completado: hitl-20260908-214515.",
      ghPaths: "Rutas relevantes",
      fixtureMap: "Mapa fixture → hallazgo",
      humanDecisionsHeading: "Decisiones humanas",
      agentLabelsHeading: "Etiquetas del agente",
      quizHeading: "Cuestionario (5 preguntas)",
    },
  },

  ghLinks: [
    { path: "fixtures/sample-dataroom/", descEn: "Synthetic VertiGreen dataroom", descEs: "Dataroom sintético VertiGreen" },
    { path: "understanding-lab/playground/", descEn: "LexiScan house-tour playground (this app)", descEs: "Playground house-tour LexiScan (esta app)" },
    { path: "hitl/microworld/", descEn: "Legacy tabbed shell (redirect)", descEs: "Shell con pestañas legacy (redirección)" },
    { path: "scripts/push_microworld_to_notion.py", descEn: "Push locks to Notion (env token)", descEs: "Enviar bloqueos a Notion" },
  ],
};
